language: rust
rust:
  - stable
  - nightly
os:
  - linux
  - windows
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
script:
  - cargo build --verbose --all
  - cargo test --verbose --all
