[package]
edition = "2018"
name = "sic"
version = "0.10.1"
authors = ["Martijn Gribnau <garm@ilumeo.com>"]
description = "Accessible image processing and conversion from the terminal (and a front-end for the 'image' crate)."
license = "MIT"
repository = "https://github.com/foresterre/sic"
readme = "README.md"
exclude = [
    ".idea/*",
    ".vscode/*",
    "*.iml",
]
keywords = ["image", "converter", "cli", "front-end", "image-cli"]
categories = ["multimedia::images", "command-line-utilities"]

[workspace]
members = [
  "components/sic_core",
  "components/sic_image_engine",
  "components/sic_io",
  "components/sic_parser",
  "components/sic_testing",
]

[dependencies]
sic_core = { path = "components/sic_core", version = "0.10" }
sic_image_engine = { path = "components/sic_image_engine", version = "0.10" }
sic_io  = { path = "components/sic_io", version = "0.10" }
sic_parser = { path = "components/sic_parser", version = "0.10" }

anyhow = "1.0"
atty = "0.2.14"
clap = "2.32.0"
inflate = "0.4.5"

[dev-dependencies]
sic_testing = { path = "components/sic_testing" }

[build-dependencies]
flate2 = "1.0.13"

[[bin]]
name = "sic"
path = "src/main.rs"

[lib]
name = "sic_lib"
path = "src/lib.rs"

[features]
output-test-images = []

[profile.release]
panic = "abort"
#lto = true
#codegen-units = 1

