[package]
edition = "2018"
name = "sic"
version = "0.9.0"
authors = ["Martijn Gribnau <garm@ilumeo.com>"]
description = "'sic' or 'sic image cli' is a (partial) front-end for the 'image' crate."
license = "MIT"
repository = "https://github.com/foresterre/sic"
readme = "README.md"
exclude = [
    ".idea/*",
    ".vscode/*",
    "*.iml",
]
keywords = ["image", "converter", "cli", "front-end", "image-cli"]
categories = ["multimedia::images", "command-line-utilities"]

[workspace]
members = [
  "sic_core",
  "sic_parser",
  "sic_user_manual",
]

[dependencies]
clap = "2.32.0"
sic_core = { path = "sic_core" }
sic_parser = { path = "sic_parser" }
sic_user_manual  = { path = "sic_user_manual" }

[[bin]]
name = "sic"
path = "src/main.rs"

[lib]
name = "sic_lib"
path = "src/lib.rs"

[features]
output-test-images = []


[profile.release]
panic = "abort"
