[package]
edition = "2018"
name = "sic"
version = "0.12.0"
authors = ["Martijn Gribnau <garm@ilumeo.com>"]
description = "Accessible image processing and conversion from the terminal (and a front-end for the 'image' crate)."
license = "MIT OR Apache-2.0"
repository = "https://github.com/foresterre/sic"
readme = "README.md"
exclude = [
    ".idea/*",
    ".vscode/*",
    "*.iml",
    ".travis.yml",
    "RELEASE_STEPS.md",
]
keywords = ["image", "converter", "cli", "front-end", "image-cli"]
categories = ["multimedia::images", "command-line-utilities"]

[workspace]
members = [
  "components/sic_cli_ops",
  "components/sic_core",
  "components/sic_image_engine",
  "components/sic_io",
  "components/sic_parser",
  "components/sic_testing",
]

[dependencies]
sic_cli_ops = { version = "0.12.0", path = "components/sic_cli_ops" }
sic_core = { version = "0.12.0", path = "components/sic_core" }
sic_io  = { version = "0.12.0", path = "components/sic_io" }
sic_image_engine = { version = "0.12.0", path = "components/sic_image_engine" }
sic_parser = { version = "0.12.0", path = "components/sic_parser"}

anyhow = "1.0.32"
atty = "0.2.14"
clap = "2.32.0"
inflate = "0.4.5"
globwalk = "0.8.0"
strum = "0.18.0"

[dev-dependencies]
sic_core = { version = "0.12.0", path = "components/sic_core" }
clap = "2.33.0" # for examples/gen_completions.rs
parameterized = "0.2.0"

[build-dependencies]
flate2 = "1.0.16"

[features]
imageproc-ops = ["sic_cli_ops/imageproc-ops", "sic_image_engine/imageproc-ops", "sic_parser/imageproc-ops"]

output-test-images = []

[profile.release]
panic = "abort"
lto = true
codegen-units = 1

