[package]
edition = "2018"
name = "sic"
version = "0.9.0"
authors = ["Martijn Gribnau <garm@ilumeo.com>"]
description = "'sic' or 'sic image cli' is a (partial) front-end for the 'image' crate."
license = "MIT"
repository = "https://github.com/foresterre/sic"
readme = "README.md"
exclude = [
    ".idea/*",
    ".vscode/*",
    "*.iml",
]
keywords = ["image", "converter", "cli", "front-end", "image-cli"]
categories = ["multimedia::images", "command-line-utilities"]

[workspace]
members = [
  "sic_core",
  "sic_parser",
  "sic_user_manual",

  # former combostew modules
  "sic_image_engine",
  "sic_io",

  "sic_testing",
]

[dependencies]
sic_core = { path = "sic_core" }
sic_image_engine = { path = "sic_image_engine" }
sic_io  = { path = "sic_io" }
sic_parser = { path = "sic_parser" }
sic_user_manual  = { path = "sic_user_manual" }

clap = "2.32.0"
inflate = "0.4.5"

[dev-dependencies]
sic_testing = { path = "sic_testing" }

[build-dependencies]
flate2 = "1.0.11"

[[bin]]
name = "sic"
path = "src/main.rs"

[lib]
name = "sic_lib"
path = "src/lib.rs"

[features]
output-test-images = []

[profile.release]
panic = "abort"
#lto = true
#codegen-units = 1