[package]
name = "sic"
version = "0.7.2"
authors = ["Martijn Gribnau <garm@ilumeo.com>"]
description = "`sic` stands for simple image converter and is a partial front-end for the `image` crate."
license = "MIT"
repository = "https://github.com/foresterre/sic"
readme = "README.md"
exclude = [
    ".idea/*",
    ".vscode/*",
    "imgconv.iml",
]
keywords = ["image", "converter", "cli", "front-end", "image-cli"]
categories = ["multimedia::images", "command-line-utilities"]

[features]
output-test-images = []

[dependencies]
arrayvec = "0.4.7"
clap = "2.32.0"
image = "0.19.0"
pest = "1.0.6"
pest_derive = "1.0.7"

[[bin]]
name = "sic"
path = "src/main.rs"