[advisories]
ignore = [
    "RUSTSEC-2021-0139", # unmaintained crate ansi_term
    "RUSTSEC-2021-0145", # unmaintained crate rusttype
    "RUSTSEC-2024-0375", # https://rustsec.org/advisories/RUSTSEC-2024-0375 `atty` is unmaintained (via `clap`)
    "RUSTSEC-2024-0436", # unmaintained crate paste
]

[licenses]
confidence-threshold = 0.925
allow = [
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "CC0-1.0",
    "MIT",
    "NCSA",
    "Unlicense",
    "Zlib",
    "Unicode-3.0",
]

[[licenses.clarify]]
name = "exr"
expression = "BSD-3-Clause"
license-files = [
    { path = "LICENSE.md", hash = 0xf0600744 },
]
