[package]
name = "sic_image_engine"
version = "0.1.0"
authors = ["Martijn Gribnau <garm@ilumeo.com>"]
edition = "2018"
license-file = "../LICENSE"

[dependencies]
sic_core = { path = "../sic_core" }

[features]
output-test-images = []