[package]
name = "sic_image_engine"
version = "0.22.1"
authors = ["Martijn Gribnau <garm@ilumeo.com>"]
description = "Component of the sic cli: provides abstractions for (the application of) image operations."
license = "MIT OR Apache-2.0"
repository = "https://github.com/foresterre/sic"
readme = "../../README.md"

edition = "2021"
rust-version = "1.61"

[dependencies]
sic_core = { version = "0.22.0", path = "../sic_core" }
sic_io = { version = "0.22.0", path = "../sic_io" }

strum = "0.26.3"
strum_macros = "0.26.4"
thiserror = "1"

rayon = "1.10.0"

[dev-dependencies]
sic_testing = { version = "0.22.0", path = "../sic_testing" }

[features]
imageproc-ops = ["sic_core/imageproc-ops"]

output-test-images = []
