[package]
name = "sic_parser"
version = "0.1.0"
authors = ["Martijn Gribnau <garm@ilumeo.com>"]
edition = "2018"
license-file = "../LICENSE"

[dependencies]
sic_core = { path = "../sic_core" }
sic_image_engine = { path = "../sic_image_engine" }
pest = "2.0.2"
pest_derive = "2.0.1"