[package]
name = "sic_cli_ops"
version = "0.12.0"
authors = ["Martijn Gribnau <garm@ilumeo.com>"]
description = "Component of the sic cli: parses images operations invoked from the cli."
edition = "2018"
license = "MIT"
repository = "https://github.com/foresterre/sic"

[dependencies]
sic_image_engine = { version = "0.12.0", path = "../../components/sic_image_engine" }
sic_parser = { version = "0.12.0", path = "../../components/sic_parser" }

clap = "2.33.0"
strum = "0.19.1"
strum_macros = "0.19.1"
thiserror = "1.0.20"

[dev-dependencies]
sic_core = { version = "0.12.0", path = "../../components/sic_core" }
sic_testing = { version = "0.12.0", path = "../../components/sic_testing" }
parameterized = "0.2.0"

[features]
imageproc-ops = []
