[package]
name = "sic_cli_ops"
version = "0.11.0-dev"
authors = ["Martijn Gribnau <garm@ilumeo.com>"]
description = "Component of the sic cli: parses images operations invoked from the cli."
edition = "2018"
license-file = "../../LICENSE"
repository = "https://github.com/foresterre/sic"

[dependencies]
sic_image_engine = { path = "../../components/sic_image_engine", version = "0.10" }
sic_parser = { path = "../../components/sic_parser", version = "0.10" }

clap = "2.33.0"
strum = "0.18.0"
strum_macros = "0.18.0"
thiserror = "1.0.16"

[dev-dependencies]
sic_cli = { path = "../../components/sic_cli" } # careful! potential circular dependency!
sic_testing = { path = "../../components/sic_testing" }
