name: msrv
on:
  pull_request:
  push:
    branches:
      - main
  merge_group:
  schedule:
    - cron: '00 06 * * *'
jobs:
  msrv_stable:
    name: msrv_stable
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: checkout_repo
        uses: actions/checkout@v4

      - name: install_rust
        uses: dtolnay/rust-toolchain@stable

      - name: install_cargo_msrv
        run: cargo install cargo-msrv # 0.17.1

      - name: version_of_cargo_msrv
        run: cargo msrv --version

      - name: install_nasm
        uses: ilammy/setup-nasm@v1

      - name: run_cargo_msrv_verify
        run: cargo msrv verify --output-format json

      - name: run_cargo_msrv_on_verify_failure
        if: ${{ failure() }}
        run: cargo msrv find --output-format json
