name: test
on:
  pull_request:
  push:
    branches:
      - main
  merge_group:
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        build: [ ubuntu-stable, macos-stable, win-gnu-stable, win-msvc-stable ]
        include:
          - build: ubuntu-stable
            os: ubuntu-latest
            rust: stable

          - build: macos-stable
            os: macos-latest
            rust: stable

          - build: win-gnu-stable
            os: windows-latest
            rust: stable-x86_64-gnu

          - build: win-msvc-stable
            os: windows-latest
            rust: stable

    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout_repository
        uses: actions/checkout@v4

      - name: install_rust_toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}

      - name: install_nasm
        uses: ilammy/setup-nasm@v1

      - name: fetch
        run: cargo fetch --verbose

      - name: build
        run: cargo build --verbose --all

      - name: test_all
        run: cargo test --verbose --all

      - name: build_(no_default_features)
        run: cargo build --verbose --all --no-default-features

      - name: test_all_(no_default_features)
        run: cargo test --verbose --all --no-default-features

      - name: build_(all_features)
        run: cargo build --verbose --all --all-features

      - name: test_all_(all_features)
        run: cargo test --verbose --all --all-features
